### ISSUE TITLE
Email form results

### ISSUE THREAD

**Issue by franc3000** [franc3000/investigator#2]
Email to: franklin.sarkett@gmail.com

Something like this:
https://www.boxcontrol.net/adding-contact-form-to-your-site-using-flask-and-python3.html

**Comment by franc3000** [comment]
Something like this:
https://www.boxcontrol.net/adding-contact-form-to-your-site-using-flask-and-python3.html

**Comment by franc3000** [comment]
Use Flask-Mail to avoid SMTP server account, user name and password.
https://pythonhosted.org/flask-mail/

**Comment by nmb10** [comment]
@franc3000 There is no email field in the form. Is it bug? How will you answer to the questions?

**Comment by nmb10** [comment]
Done. Email settings documented [here](https://github.com/franc3000/investigator#environment-variables-with-email-settings).
